### ISSUE TITLE
Fail to install github desktop

### ISSUE THREAD

**Issue by chcao052** [githubteacher/devs-feb-2017#3]
Here is the log:

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1087.0 built by: NETFXREL4STAGE
	clr.dll 			: 4.6.1087.0 built by: NETFXREL4STAGE
	dfdll.dll 			: 4.6.1087.0 built by: NETFXREL4STAGE
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: http://github-windows.s3.amazonaws.com/GitHub.application
						Server		: AmazonS3
	Application url			: http://github-windows.s3.amazonaws.com/Application%20Files/GitHub_3_3_4_0/GitHub.exe.manifest
						Server		: AmazonS3

IDENTITIES
	Deployment Identity		: GitHub.application, Version=3.3.4.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86
	Application Identity		: GitHub.exe, Version=3.3.4.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://github-windows.s3.amazonaws.com/GitHub.application resulted in exception. Following failure messages were detected:
		+ Downloading http://github-windows.s3.amazonaws.com/Application Files/GitHub_3_3_4_0/Microsoft.WindowsAPICodePack.Shell.dll.deploy did not succeed.
		+ The operation has timed out.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [22/02/2017 10:21:04 AM] : Activation of http://github-windows.s3.amazonaws.com/GitHub.application has started.
	* [22/02/2017 10:21:05 AM] : Processing of deployment manifest has successfully completed.
	* [22/02/2017 10:21:05 AM] : Installation of the application has started.
	* [22/02/2017 10:21:05 AM] : Processing of application manifest has successfully completed.
	* [22/02/2017 10:21:12 AM] : Found compatible runtime version 4.0.30319.
	* [22/02/2017 10:21:12 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [22/02/2017 10:26:48 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://github-windows.s3.amazonaws.com/Application Files/GitHub_3_3_4_0/Microsoft.WindowsAPICodePack.Shell.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The operation has timed out.
		- Source: System
		- Stack trace:
			at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by pqtuan** [comment]
Same here

**Comment by 1rgy** [comment]
It failed for me too after downloading apparently 126/127Mb. I assume it's happening to everyone. It doesn't seem to matter if it's o drive or from the web since they both run the same downloader

**Comment by LokiTrickster** [comment]
Yep, same here, Irgy.

**Comment by dkarlov-cisra** [comment]
I'm also having 1rgy's problem with a download that doesn't complete

**Comment by 1rgy** [comment]
FYI we do have this:
O:\general\software\GitHub\Git\2.9.0

**Comment by junliu93** [comment]
This one works well with power shell.

**Comment by githubteacher** [comment]
Thanks @1rgy 
:octocat: :sparkling_heart:

**Comment by albchang** [comment]
Stephen from IT is looking into the issue of GitHub Desktop

**Comment by jiulun** [comment]
I have just installed the GitHub Desktop successfully.

**Comment by albchang** [comment]
I can confirm that it now works. :+1:
